version: "3.7"
services:
  dotfiles:
    image: ghcr.io/wbelucky/dotfiles-with-docker:latest
    stdin_open: true
    tty: true
    volumes:
      - .:/home/${USERNAME:-user}/dotfiles
    environment:
      - SSH_TTY
      - LOCAL_UID=1000
      - LOCAL_GID=1000
