version: "3.3"
services:
  dev:
    image: ghcr.io/wbelucky/dotfiles-with-docker:latest
    stdin_open: true
    tty: true
    volumes:
      - .:/home/${USERNAME:-user}/dotfiles
    user: ${USERNAME:-user}

