version: "3.3"
services:
  dev:
    build:
      context: .
      dockerfile: base.Dockerfile
      args:
        - USERNAME=${USERNAME:-user}
    stdin_open: true
    tty: true
    volumes:
      - .:/home/${USERNAME:-user}/dotfiles
    user: ${USERNAME:-user}
