version: "3.3"
services:
  base:
    build:
      context: .
      dockerfile: base.Dockerfile
      args:
        - USERNAME=${USERNAME:-user}
    stdin_open: true
    tty: true
    volumes:
      - .:/home/${USERNAME:-user}/dotfiles
    user: ${USERNAME:-user}
  dev:
    image: ghcr.io/wbelucky/dotfiles-with-docker:latest
    stdin_open: true
    tty: true
    volumes:
      - .:/home/${USERNAME:-user}/dotfiles
    user: ${USERNAME:-user}

